baseURL = "https://www.drurathror.com"
title = "drurathror"
theme = "m10c"
paginate = 5

[params]
  author = "drurathror"
  description = "/dev/random"
  [[params.social]]
    name = "mail"
    url = "drurathror@protonmail.com"
  [[params.social]]
    name = "key"
    url = "/drurathror.txt"
  [[params.social]]
    name = "rss"
    url = "https://www.drurathror.com/index.xml"
  [[params.social]]
    name = "github"
    url = "https://github.com/drurathror"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/drurathror"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
